## 자료형 변수

### 튜플

- 전체 데이터 수 검색

In [1]:
data = (100,200,100,300,100,500)
print(type(data))
print(data.count(100))

<class 'tuple'>
3


In [3]:
data = (100,200,100,300,100,500)
print(data[2:4])

(100, 300)


In [4]:
d1=('사과','배')
d2=(100,200,300)
d=d1+d2
print(d)

('사과', '배', 100, 200, 300)


In [5]:
d=('사과','배','포도')
print(d*2)

('사과', '배', '포도', '사과', '배', '포도')


### 세트

In [7]:
d={100,200,300}
print(d)
print(type(d))

{200, 100, 300}
<class 'set'>


세트는 순서가 없기 떄문에 인덱싱 불가

- 데이터 추가

In [9]:
d={100,200,300,400,500,600}
print(d)
d.add(700)
print(d)

{100, 200, 300, 400, 500, 600}
{100, 200, 300, 400, 500, 600, 700}


- 데이터 업데이트 / 삭제 / 초기화

In [11]:
d={100}
d.update([200,300,400,500,600])
print(d)

{100, 200, 300, 400, 500, 600}


In [13]:
d={100,200,300,400,500,600}
d.remove(600)
print(d)

{100, 200, 300, 400, 500}


In [ ]:
d={100,200,300,400,500,600}
data.clear()

- 세트의 집합연산

In [ ]:
# 교집합 : print(A.intersection(B))
# 차집합 : print(A.difference(B))
# 합집합 : print(A.union(B)
# 합 - 교 : print(A.symmetric_difference(B)

### 딕셔너리

- 연산

In [ ]:
# 검색 : print(data["사과"]) 또는 print(data.get("사과"))
# 추가 : data["메론"]=1000
# 삭제 : data.pop.("사과")
# 정렬 : sorted(data) , sorted(data.values())

## 제어문 및 반복문, 함수

In [14]:
# if
# while
# for

In [15]:
# 함수
# lambda

- 라이버리, 리패키지

In [16]:
# 내부, 외부

### NumPy, Pandas

### 1) NumPy

In [17]:
np=[1.0, 10.4, 3.2, 5.1, 2.7]

flotV = [np,np,np]
flotV

[[1.0, 10.4, 3.2, 5.1, 2.7],
 [1.0, 10.4, 3.2, 5.1, 2.7],
 [1.0, 10.4, 3.2, 5.1, 2.7]]

- NumPy.ndarray

In [18]:
import numpy as np

a=np.array([1, 2.5, 4.0, 5.5, 7.0])
a[3:]

array([5.5, 7. ])

In [ ]:
a=sum() # np.array로 생성된 a의 합
a=std() # 표준편차
a=cumsum() # 누적합

- axis

In [20]:
b=np.array([a,a**2])
b

array([[ 1.  ,  2.5 ,  4.  ,  5.5 ,  7.  ],
       [ 1.  ,  6.25, 16.  , 30.25, 49.  ]])

In [21]:
b.sum(axis=0) # 종

array([ 2.  ,  8.75, 20.  , 35.75, 56.  ])

In [22]:
b.sum(axis=1) # 횡

array([ 20. , 102.5])

In [23]:
values=np.zeros((2,3))
values

array([[0., 0., 0.],
       [0., 0., 0.]])

### 2) Pandas

- Series

In [25]:
import pandas as pd

pandas_series = pd.Series([3000,3200,2700],
                index=['2016-11-10','2016-11-11','2016-11-12'])
pandas_series

2016-11-10    3000
2016-11-11    3200
2016-11-12    2700
dtype: int64

In [26]:
pandas_series[1:]

2016-11-11    3200
2016-11-12    2700
dtype: int64

- Data Frame

In [27]:
import pandas as pd

df = pd.DataFrame([100,150,200,250,300], columns=['numbers'],
                 index=['a','b','c','d','e'])
df

numbers
a      100
b      150
c      200
d      250
e      300

In [30]:
df.index
df.columns
df.ix['c']

AttributeError: 'DataFrame' object has no attribute 'ix'